version: '2'

syncs:
  sync-volume:
    src: '.'
    sync_strategy: 'unison'
    sync_excludes: ['.gitignore', '.git/', '.idea/', 'volumes/*']
    watch_excludes: ['.gitignore', '.git/', '.idea/', 'volumes/*'] 
    watch_args: '-v' 
    watch_strategy: 'fswatch'